version: "3"

services:
  mininet:
    image: opennetworking/ngsdn-tutorial:stratum_bmv2
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
    entrypoint: "/mininet/topo.py"
    network_mode: "host"
    
  onos:
    image: onosproject/onos:2.2.2
    hostname: onos
    container_name: onos
    network_mode: "host"
    volumes:
      - ./tmp/onos:/root/onos/apache-karaf-4.2.8/data/tmp
      - ./config:/config 
    environment:
      - ONOS_APPS=gui2,drivers.bmv2,lldpprovider,hostprovider
